### ALL ORDER
GET http://localhost:8080/order

### ADD ORDER
POST http://localhost:8080/order/addorder
Content-Type: application/json

{
    "userId": 1,
    "productId": 1,
    "orderquantity": 9
}

### DELETE ORDER
POST http://localhost:8080/order/deleteorder
Content-Type: application/json

{
    "productId": 9
}

### UPDATE ORDER
POST http://localhost:8080/order/updateorder
Content-Type: application/json

{
    "productId": 9,
    "orderquantity": 1
}