 ### LOGIN
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "admin",
    # "phoneNum": "0123456789",
    # "email": "admin@gmail.com",
    "password": "admin"
}

### REGISTER
POST http://localhost:8080/user/register
Content-Type: application/json

{
    "name": "admin",
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "admin",
    "name": "admin",
    "adress": "admin adress",
    "phoneNum": "012345678",
    "role": "admin",
    "checkVerify": "verify needed"
}

### LOGOUT
DELETE http://localhost:8080/user/logout
Content-Type: application/json

{
    "id": 59
}

### FORGOT PASSWORD
POST http://localhost:8080/user/forgot
Content-Type: application/json

{
    "email": "admin@gmail.com"
}


### RESET PASSWORD
POST http://localhost:8080/user/resetpassword?resetpassword=1
Content-Type: application/json

{
    "password": "admin"
}

### DELETE USER
DELETE http://localhost:8080/user/delete/8
Content-Type: application/json

### UPDATE USER
### UPDATE NAME
http://localhost:8080/user/update
Content-Type: application/json

{
    "userId": "1",
    "name": "customer"
}

### UPDATE ADDRESS
http://localhost:8080/user/update
Content-Type: application/json

{
    "userId": "1",
    "adress": "115 Ton Duc Thang"
}

### UPDATE EMAIL
http://localhost:8080/user/update
Content-Type: application/json

{
    "userId": "1",
    "email": "admin@gmai.com"
}

### UPDATE PHONE NUMBER
http://localhost:8080/user/update
Content-Type: application/json

{
    "userId": "1",
    "phoneNum": "0123456789"
}

### UPDATE PASSWORD
http://localhost:8080/user/update
Content-Type: application/json

{
    "userId": "1",
    "password": "123456"
}